module.exports = {
    name: 'd2',
	description: 'List of Dust 2 flashbangs.',
	aliases:  ['dust'],
	execute(messageFlash, argsflash) {
			if (!argsflash.lenght){ 
				messageFlash.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of all Dust 2 flashbangs.",
				fields: [
					{name: "d2-goose, dust-goose",
					value: "A Site flash from Goose."},
					{name: "d2-a-retake, dust-a-retake",
					value: "A Site retake flash from CT."},
					{name: "d2-b, dust-b",
					value: "B Site flash from Upper Tunnels."},
					{name: "d2-b-retake, dust-b-retake",
					value: "B Site retake flash from Mid."},
					{name: "d2-b-rush, dust-b-rush",
					value: "B Site rush flash from Upper Tunnels."},
					{name: "d2-cross, dust-cross",
					value: "A Long cross flash from A Long."},
					{name: "d2-long-barrel, dust-long-barrel",
					value: "A Long flash from A Long Barrel."},
					{name: "d2-long-ct, dust-long-ct",
					value: "A Long flash from CT."},
					{name: "d2-long-doors, dust-long-doors",
					value: "A Long flash from Outside Long Doors."},
					{name: "d2-long-a, dust-long-a",
					value: "A Long flash from A Site."},
					{name: "d2-long, dust-long",
					value: "A Long flash from Outside Long."},
					{name: "d2-long-pop, dust-long-pop",
					value: "A Long pop flash from CT."},
					{name: "d2-mid-ct, dust-mid-ct",
					value: "Mid flash from CT."},
					{name: "d2-mid-lower, dust-mid-lower",
					value: "Mid flash from Lower Tunnels."},
					{name: "d2-mid-top, dust-mid-top",
					value: "Mid flash from Top Mid."},
					{name: "d2-mid-b, dust-mid-b",
					value: "Mid to B flash from Xbox."},
					{name: "d2-mid, dust-mid",
					value: "Mid flash from Bottom Mid."},
					{name: "d2-short-a, dust-short-a",
					value: "A Short flash from A Site."},
					{name: "d2-short-lower, dust-short-lower",
					value: "A Short flash from Lower Tunnels."},
					{name: "d2-short, dust-short",
					value: "A Short flash from Catwalk/Elbow."},
					{name: "d2-upper, dust-upper",
					value: "Upper Tunnels flash from B Site."},
			]}})}}}