module.exports = {
    name: 'mirage',
	description: 'List of Inferno smokes.',
	aliases:  ['mrg'],
	execute(message, args) {
			if (!args.lenght){ 
			// A Site smokes
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Mirage smokes for the A Bomb-Site.",
				fields: [
					{name: "mirage-a-fast, mrg-a-fast",
					value: "A Bomb Site smoke for fast plant from A Ramp."},
					{name: "mirage-cross, mrg-cross",
					value: "A Bomb Site cross smoke from Underpass."},
					{name: "mirage-cross-catwalk, mrg-cross-catwalk",
					value: "A Bomb Site cross smoke from Catwalk. Smoke blocks vision from Ticket and offers a one-way towards Triple Box."},
					{name: "mirage-ct, mrg-ct",
					value: "CT smoke from T Spawn."},
					{name: "mirage-ct-tetris, mrg-ct-tetris",
					value: "CT smoke from Tetris."},
					{name: "mirage-jungle, mrg-jungle",
					value: "Jungle smoke from A Ramp."},
					{name: "mirage-jungle-tetris, mrg-jungle-tetris",
					value: "Jungle smoke from Tetris."},
					{name: "mirage-palace-conn, mrg-palace-conn",
					value: "Palace smoke from Top Connector."},
					{name: "mirage-palace-kitchen, mrg-palace-kitchen",
					value: "Palace support smoke from Outside Kitchen."},
					{name: "mirage-palace-under, mrg-palace-under",
					value: "Palace smoke from Under Balcony."},
					{name: "mirage-ramp, mrg-ramp",
					value: "Ramp smoke from CT."},
					{name: "mirage-stairs, mrg-stairs",
					value: "Stairs smoke from A Ramp."},
					{name: "mirage-topconn-tetris, mrg-topconn-tetris",
					value: "Top Connector smoke from Tetris."},
			]}})
			// B Site smokes
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Mirage smokes for the B Bomb-Site.",
				fields: [
					{name: "inferno-b-ct, inf-b-ct",
					value: "B Site entrance smoke from CT."},
					{name: "inferno-b-oranges, inf-b-oranges",
					value: "B Site entrance smoke from Oranges."},
					{name: "inferno-b-retake, inf-b-retake",
					value: "B Site retake smoke from Motorway. Smoke blocks vision from the entire site."},
					{name: "inferno-b-wall1, inf-b-wall1",
					value: "B Site smoke wall. First of the two smokes."},
					{name: "inferno-b-wall2, inf-b-wall2",
					value: "B Site smoke wall. Second of the two smokes."},
					{name: "inferno-banana-ct, inf-banana-ct",
					value: "Banana fast smoke from CT."},
					{name: "inferno-banana-deep, inf-banana-deep",
					value: "Banana deep smoke from B Site entrance."},
					{name: "inferno-banana-oneway, inf-banana-oneway",
					value: "Banana one-way smoke from Sandbags."},
					{name: "inferno-coffins, inf-coffins",
					value: "Coffins smoke from Banana."},
					{name: "inferno-ct, inf-ct",
					value: "CT smoke from Banana."},
			]}})
			// Mid smokes
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Mirage smokes for Mid.",
				fields: [
					{name: "mirage-catwalk, mrg-catwalk",
					value: "Catwalk smoke from B Short."},
					{name: "mirage-conn-spawn, mrg-conn-spawn",
					value: "Connector smoke from T Spawn."},
					{name: "mirage-mid, mrg-mid",
					value: "Top Mid smoke from T Spawn."},
					{name: "mirage-short-mid, mrg-short-mid",
					value: "Short smoke from Top Mid."},
					{name: "mirage-short-under, mrg-short-under",
					value: "Short smoke from Underpass/Bottom Mid."},
					{name: "mirage-window-mid, mrg-window-mid",
					value: "Window smoke from Top Mid."},
					{name: "mirage-window-spawn, mrg-window-spawn",
					value: "Window smoke from T Spawn."},
					{name: "mirage-window-under, mrg-window-under",
					value: "Window smoke from Underpass."},
			]}})
		}}}