module.exports = {
    name: 'd2',
	description: 'List of Dust 2 smokes.',
	aliases:  ['dust'],
	execute(message, args) {
			if (!args.lenght){ 
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Dust 2 smokes.",
				fields: [
					{name: "d2-a-cross1, dust-a-cross1",
					value: "CT Cross smoke for Terrorists on A Long. First of the two smokes."},
					{name: "d2-a-cross2, dust-a-cross2",
					value: "CT Cross smoke for Terrorists on A Long. Second of the two smokes."},
					{name: "d2-b-cross, dust-b-cross",
					value: "B Cross smoke from Tunnels for execute."},
					{name: "d2-door, dust-door",
					value: "B Doors smoke from Tunnels."},
					{name: "d2-lurk, dust-lurk",
					value: "Outisde Upper Tunnels smoke for B execute/lurk."},
					{name: "d2-upper, dust-upper",
					value: "B Tunnel smoke from Mid (for retake or resmoke)."},
					{name: "d2-window, dust-window",
					value: "B Window smoke from Boost."},
					{name: "d2-ct-cross, dust-ct-cross",
					value: "CT Cross smoke from CT Spawn to safely cross to B site."},
					{name: "d2-ct-long, dust-ct-long",
					value: "CT smoke from A Long."},
					{name: "d2-mid-b, dust-mid-b",
					value: "CT smoke for a Mid to B execute/split."},
					{name: "d2-mid-bbox, dust-mid-bbox",
					value: "Smoke for CT Box above the CT Mid-to-B smoke. Prevents CTs from jumping on the box and spotting Ts."},
					{name: "d2-ct-short, dust-ct-short",
					value: "CT smoke from A Short."},
					{name: "d2-hinge, dust-hinge",
					value: "Mid Doors hinge smoke to safely get up Catwalk."},
					{name: "d2-long-car, dust-long-car",
					value: "A Long Doors smoke from Car."},
					{name: "d2-long-fast, dust-long-fast",
					value: "A Long Doors smoke from Elevator."},
					{name: "d2-long-oneway, dust-long-oneway",
					value: "A Long Doors one-way smoke from Car that lands on the barrel."},
					{name: "d2-long, dust-long",
					value: "A Long corner smoke from T-Spawn."},
					{name: "d2-lower, dust-lower",
					value: "Lower Tunnels lurk smoke from CT."},
					{name: "d2-pit, dust-pit",
					value: "Pit smoke from Outside Long to avoid getting spotted by the pit player in HS angle."},
					{name: "d2-short, dust-short",
					value: "A Short smoke from A Site."},
					{name: "d2-short-deep, dust-short-deep",
					value: "A Short deep smoke from A Site."},
					{name: "d2-short-lurk, dust-short-lurk",
					value: "A Short one-way smoke for A executes or lurks. Can also be used on retake."},
					{name: "d2-xbox, d2-xbox",
					value: "Xbox smoke from T-Spawn."},
					{name: "d2-xbox-long, dust-xbox-long",
					value: "Xbox smoke from Outside Long."},
					{name: "d2-xbox-lower, d2-xbox-lower",
					value: "Xbox smoke from Lower Tunnels"},
			]}})}}}