module.exports = {
    name: 'd2',
	description: 'List of Dust 2 smokes.',
	aliases:  ['dust'],
	execute(message, args) {
			if (!args.lenght){ 
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Dust 2 smokes.",
				fields: [
					{name: "dust-a-cross1, d2-a-cross1",
					value: "CT Cross smoke for Terrorists on A Long. First of the two smokes."},
					{name: "dust-a-cross2, d2-a-cross2",
					value: "CT Cross smoke for Terrorists on A Long. Second of the two smokes."},
					{name: "dust-b-cross, d2-b-cross",
					value: "B Cross smoke from Tunnels for execute."},
					{name: "dust-b-doors, d2-b-doors",
					value: "B Doors smoke from Tunnels."},
					{name: "dust-b-lurk, d2-b-lurk",
					value: "Outisde Upper Tunnels smoke for B execute/lurk."},
					{name: "dust-upper, d2-upper",
					value: "B Tunnel smoke from Mid (for retake or resmoke)."},
					{name: "dust-window, d2-window",
					value: "B Window smoke from Boost."},
					{name: "dust-ct-cross, d2-ct-cross",
					value: "CT Cross smoke from CT Spawn to safely cross to B site."},
					{name: "dust-ct-long, d2-ct-long",
					value: "CT smoke from A Long."},
					{name: "dust-mid-b, d2-mid-b",
					value: "CT smoke for a Mid to B execute/split."},
					{name: "dust-mid-bbox, d2-mid-bbox",
					value: "Smoke for CT Box above the CT Mid-to-B smoke. Prevents CTs from jumping on the box and spotting Ts."},
					{name: "dust-ct-short, d2-ct-short",
					value: "CT smoke from A Short."},
					{name: "dust-hinge, d2-hinge",
					value: "Mid Doors hinge smoke to safely get up Catwalk."},
					{name: "dust-long-car, d2-long-car",
					value: "A Long Doors smoke from Car."},
					{name: "dust-long-fast, d2-long-fast",
					value: "A Long Doors smoke from Elevator."},
					{name: "dust-long, d2-long",
					value: "A Long corner smoke from Outside Long."},
					{name: "dust-lower, d2-lower",
					value: "Lower Tunnels lurk smoke from CT."},
					{name: "dust-pit, d2-pit",
					value: "Pit smoke from Outside Long to avoid getting spotted by the pit player in HS angle."},
					{name: "dust-short, d2-short",
					value: "A Short smoke from A Site."},
					{name: "dust-short-deep, d2-short-deep",
					value: "A Short deep smoke from A Site."},
					{name: "dust-short-lurk, d2-short-lurk",
					value: "A Short one-way smoke for A executes or lurks. Can also be used on retake."},
					{name: "dust-xbox, d2-xbox",
					value: "Xbox smoke from T-Spawn."},
					{name: "dust-xbox-long, d2-xbox-long",
					value: "Xbox smoke from Outside Long."},
					{name: "dust-xbox-lower, d2-xbox-lower",
					value: "Xbox smoke from Lower Tunnels"},
			]}})}}}
