module.exports = {
    name: 'inferno',
	description: 'List of Inferno smokes.',
	aliases:  ['inf'],
	execute(message, args) {
			if (!args.lenght){ 
			// A Site smokes
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Inferno smokes for the A Bomb-Site.",
				fields: [
					{name: "inferno-a-retake, inf-a-retake",
					value: "A Site retake smoke from Motorway. Smoke blocks vision from Pit and Mini Pit."},
					{name: "inferno-apps-oneway, inf-apps-oneway",
					value: "Apartments one-way smoke from Apartments."},
					{name: "inferno-arch, inf-arch",
					value: "Arch smoke from Second Mid."},
					{name: "inferno-balcony-2nd, inf-balcony-2nd",
					value: "Balcony smoke from Second Mid."},
					{name: "inferno-balcony-arch, inf-balcony-arch",
					value: "Balcony smoke from Arch."},
					{name: "inferno-dribble, inf-dribble",
					value: "Balcony dribble smoke from Apartments."},
					{name: "inferno-library, inf-library",
					value: "Library smoke from Top Mid."},
					{name: "inferno-long-deep, inf-long-deep",
					value: "Long deep smoke from Top Mid."},
					{name: "inferno-long, inf-long",
					value: "Long smoke from Second Mid."},
					{name: "inferno-mid, inf-mid",
					value: "Top Mid smoke from T-Ramp."},
					{name: "inferno-mini, inf-mini",
					value: "Mini Pit smoke from Second Mid."},
					{name: "inferno-moto, inf-moto",
					value: "Moto smoke from Top Mid."},
					{name: "inferno-pit-oneway, inf-pit-oneway",
					value: "Big Pit one-way smoke from Big Pit."},
					{name: "inferno-pit, inf-pit",
					value: "Big Pit smoke from Second Mid."},
					{name: "inferno-short, inf-short",
					value: "Short smoke from Second Mid."},
			]}})
			// B Site smokes
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Inferno smokes for the B Bomb-Site.",
				fields: [
					{name: "inferno-b-ct, inf-b-ct",
					value: "B Site entrance smoke from CT."},
					{name: "inferno-b-oranges, inf-b-oranges",
					value: "B Site entrance smoke from Oranges."},
					{name: "inferno-b-retake, inf-b-retake",
					value: "B Site retake smoke from Motorway. Smoke blocks vision from the entire site."},
					{name: "inferno-b-wall1, inf-b-wall1",
					value: "B Site smoke wall. First of the two smokes."},
					{name: "inferno-b-wall2, inf-b-wall2",
					value: "B Site smoke wall. Second of the two smokes."},
					{name: "inferno-banana-ct, inf-banana-ct",
					value: "Banana fast smoke from CT."},
					{name: "inferno-banana-deep, inf-banana-deep",
					value: "Banana deep smoke from B Site entrance."},
					{name: "inferno-banana-oneway, inf-banana-oneway",
					value: "Banana one-way smoke from Sandbags."},
					{name: "inferno-coffins, inf-coffins",
					value: "Coffins smoke from Banana."},
					{name: "inferno-ct, inf-ct",
					value: "CT smoke from Banana."},
			]}})}}}