module.exports = {
    name: 'd2',
	description: 'List of Dust 2 molotovs.',
	aliases:  ['dust'],
	execute(message, argsmolo) {
			if (!argsmolo.lenght){ 
			message.channel.send({embed: {
				color: 7357942,
				title: "Hey future pro!",
				description: "Here's the list of Dust 2 molotovs.",
				fields: [
					{name: "d2-ramp, dust-ramp",
					value: "A Site ramp molotov from A Short."},
					{name: "d2-a-short, dust-a-short",
					value: "A Site molotov from A Short."},
					{name: "d2-b-car, dust-b-car",
					value: "B Site Car molotov from Mid."},
					{name: "d2-plat-mid, dust-plat-mid",
					value: "B Site Back Plat molotov from Mid."},
					{name: "d2-plat-upper, dust-plat-upper",
					value: "B Site Back Plat molotov from Upper Tunnels."},
					{name: "d2-b-retake, dust-b-retake",
					value: "B Site backsite retake molotov from Window."},
					{name: "d2-b-default, dust-b-default",
					value: "B Site default molotov from Window."},
					{name: "d2-upper, dust-upper",
					value: "B Site tunnels molotov from Window."},
					{name: "d2-b-xbox, dust-b-xbox",
					value: "B Site Xbox molotov from Window."},
					{name: "d2-b-left, dust-b-left",
					value: "B Site left side molotov from Upper Tunnels."},
					{name: "d2-b, dust-b",
					value: "B Site molotov from Upper Tunnels."},
					{name: "d2-car-64, dust-car-64",
					value: "A Long Car molotov from Long. (64 Tick)"},
					{name: "d2-car-128, dust-car-128",
					value: "A Long Car molotov from Long. (128 Tick)"},
					{name: "d2-cubby, dust-cubby",
					value: "Mid Doors Cubby molotov from Lower Tunnels."},
					{name: "d2-goose, dust-goose",
					value: "A Site Goose molotov from A Short."},
					{name: "d2-lower, dust-lower",
					value: "Lower Tunnels molotov from Mid."},
					{name: "d2-short-long, dust-short-long",
					value: "A Short molotov from Long Doors."},
					{name: "d2-short-top, dust-short-top",
					value: "A Short molotov from Top Mid."},
					{name: "d2-short-lower, dust-short-lower",
					value: "A Short flash from Lower Tunnels."},
					{name: "d2-short, dust-short",
					value: "A Short molotov from A Site."},
					{name: "d2-window, dust-window",
					value: "B Site Window molotov from Boost."},
					{name: "d2-xbox, dust-xbox",
					value: "A Short molotov from Mid. Burns behind Xbox smoke."},
			]}})}}}